id: I9B20C9B6
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 15:07:56.866223
last_modified: 2023-02-09 15:07:56.866349
source_metadata:
  title: 'MSV 1,09: Kośāmbakavastu'
  language: bo
bases:
  9B24:
    base_file: 9B24.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
